# Use an official Node.js runtime as the base image
FROM node:22-alpine AS builder

# Copy the rest of the application files
COPY . .

# Install dependencies
RUN npm install --frozen-lockfile

# Build the Next.js project
RUN npm run build

# Expose port 3001 to the outside world
EXPOSE 3001

# Start the Next.js production server
CMD ["npm", "run", "dev"]
