# Use an official Node.js runtime as the base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose port 3001 to the outside world
EXPOSE 3001

# Start the Next.js development server
CMD ["npm", "run", "dev", "--", "-p", "3001"]
